services:
  postgres:
    image: postgres:16
    container_name: ai-agent-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - ai_agent_postgres_data:/var/lib/postgresql/data
    networks:
      - ai-agent-net

  api:
    build:
      context: .
      dockerfile: src/AiIncidentResponseAgent.Api/Dockerfile
    container_name: ai-agent-api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      OllamaAnalyzer__Enabled: "true"
      OllamaAnalyzer__BaseUrl: ${OLLAMA_BASE_URL}
      OllamaAnalyzer__Model: llama3
      Realtime__Enabled: "true"
      Realtime__ApiBaseUrl: http://api:8080
      InternalApiKey__ApiKey: ${INTERNAL_API_KEY}
      Jwt__Issuer: AiIncidentResponseAgent
      Jwt__Audience: OpsCenter
      Jwt__Secret: ${JWT_SECRET}
      Jwt__ExpirationMinutes: 120
    ports:
      - "${API_HTTP_PORT}:8080"
    networks:
      - ai-agent-net

  worker:
    build:
      context: .
      dockerfile: src/AiIncidentResponseAgent.Worker/Dockerfile
    container_name: ai-agent-worker
    depends_on:
      - api
      - postgres
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      OllamaAnalyzer__Enabled: "true"
      OllamaAnalyzer__BaseUrl: ${OLLAMA_BASE_URL}
      OllamaAnalyzer__Model: llama3
      Realtime__Enabled: "true"
      Realtime__ApiBaseUrl: http://api:8080
      InternalApiKey__ApiKey: ${INTERNAL_API_KEY}
      AgentWorker__PollingIntervalSeconds: 5
      AgentWorker__BatchSize: 20
      AgentRetry__MaxRetries: 3
      AgentRetry__BaseDelaySeconds: 10
      AgentRetry__MaxDelaySeconds: 300
    networks:
      - ai-agent-net

  ops-center:
    build:
      context: ./ops-center
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:${API_HTTP_PORT}
    container_name: ai-agent-ops-center
    depends_on:
      - api
    ports:
      - "${OPS_CENTER_PORT}:3000"
    networks:
      - ai-agent-net


volumes:
  ai_agent_postgres_data:

networks:
  ai-agent-net:
    driver: bridge